import { CORE_VERSION } from '@gameasset-forge/core';

/**
 * Unity exporter (charter §21): generates an Editor import script that reads
 * atlas.json at import time and slices the atlas via TextureImporter. No
 * .meta files are generated (charter: never fake Unity internal state).
 *
 * Static validation only in this environment — if Unity is not installed we
 * report "export generated, runtime validation unavailable" (charter §21).
 *
 * The script uses Unity's built-in JsonUtility, which ignores unknown JSON
 * fields — so it can parse a subset of the generic atlas.json without any
 * external dependency. Note: Unity sprite rects are bottom-left origin while
 * the manifest is top-left, hence the Y flip against the page height.
 */
export function buildUnityImporterScript(): string {
  return UNITY_IMPORTER.replaceAll('@VERSION@', CORE_VERSION);
}

const UNITY_IMPORTER = `// Generated by GameAsset Forge @VERSION@ — do not edit by hand.
//
// Unity Editor importer for GameAsset Forge atlases.
// Usage: place this file (and the exported atlas-N.png + atlas.json) inside
// your Unity project, with this script under an "Editor" folder.
// Requirements: none beyond Unity 2021.3+ (uses built-in JsonUtility).
//
// The script slices every atlas-N.png according to the sibling atlas.json
// and applies per-sprite pivots. Sprite ids use '<source>#<name>' and are
// converted to '<source>/<name>' sprite names.
//
// NOTE: this generated script has passed static validation only. Runtime
// validation requires opening the project in Unity (charter: never claim
// runtime verification without the runtime).

using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace GameAssetForge
{
    internal static class ForgeManifest
    {
        [System.Serializable]
        internal class RectJson
        {
            public float x;
            public float y;
            public float width;
            public float height;
        }

        [System.Serializable]
        internal class PivotJson
        {
            public float x;
            public float y;
        }

        [System.Serializable]
        internal class SpriteEntry
        {
            public string id;
            public int page;
            public RectJson rect;
            public PivotJson pivot;
        }

        [System.Serializable]
        internal class PageEntry
        {
            public string file;
            public int width;
            public int height;
        }

        [System.Serializable]
        internal class Manifest
        {
            public List<SpriteEntry> sprites;
            public List<PageEntry> pages;
        }

        internal static Manifest Parse(string json)
        {
            return JsonUtility.FromJson<Manifest>(json);
        }
    }

    public class GameAssetForgeImporter : AssetPostprocessor
    {
        private void OnPreprocessTexture()
        {
            if (!assetPath.EndsWith(".png", System.StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            var manifestPath = Path.Combine(Path.GetDirectoryName(assetPath) ?? "", "atlas.json");
            if (!File.Exists(manifestPath))
            {
                return;
            }

            var manifest = ForgeManifest.Parse(File.ReadAllText(manifestPath));
            if (manifest == null || manifest.sprites == null || manifest.pages == null)
            {
                return;
            }

            var page = PageIndexFromFileName(assetPath);
            if (page < 0 || page >= manifest.pages.Count)
            {
                return;
            }
            var pageHeight = manifest.pages[page].height;

            var importer = (TextureImporter)assetImporter;
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Multiple;
            importer.mipmapEnabled = false;
            importer.filterMode = FilterMode.Point;
            importer.spritePixelsPerUnit = 100f;

            var meta = new List<SpriteMetaData>();
            foreach (var sprite in manifest.sprites)
            {
                if (sprite.page != page)
                {
                    continue;
                }

                // Manifest rects are top-left origin; Unity rects are bottom-left.
                var unityY = pageHeight - sprite.rect.y - sprite.rect.height;
                meta.Add(new SpriteMetaData
                {
                    name = (sprite.id ?? "sprite").Replace('#', '/'),
                    rect = new UnityEngine.Rect(sprite.rect.x, unityY, sprite.rect.width, sprite.rect.height),
                    alignment = (int)SpriteAlignment.Custom,
                    pivot = new Vector2(sprite.pivot.x, sprite.pivot.y),
                    border = Vector4.zero,
                });
            }

            importer.spritesheet = meta.ToArray();
        }

        private static int PageIndexFromFileName(string assetPath)
        {
            var name = Path.GetFileNameWithoutExtension(assetPath);
            var dash = name.LastIndexOf('-');
            if (dash < 0 || !name.StartsWith("atlas", System.StringComparison.OrdinalIgnoreCase))
            {
                return 0;
            }
            return int.TryParse(name.Substring(dash + 1), out var index) ? index : 0;
        }
    }
}
`;
