import { describe, expect, it } from 'vitest';
import { parsePreset, runPipeline, CORE_VERSION } from '@gameasset-forge/core';
import { createRasterImage, setPixel, type Pixel } from '@gameasset-forge/core';
import { buildSpriteFramesTres } from '../src/exporters/godot.js';
import { buildUnityImporterScript } from '../src/exporters/unity.js';

const RED: Pixel = [255, 0, 0, 255];
const GREEN: Pixel = [0, 255, 0, 255];

function blob(
  image: ReturnType<typeof createRasterImage>,
  x: number,
  y: number,
  w: number,
  h: number,
  color: Pixel,
): void {
  for (let dy = 0; dy < h; dy++)
    for (let dx = 0; dx < w; dx++) setPixel(image, x + dx, y + dy, color);
}

/** Two-sprite sheet → manifest, matching the godot-smoke sample layout. */
function buildManifest() {
  const image = createRasterImage(24, 8, { hasAlpha: true });
  blob(image, 2, 2, 4, 4, RED);
  blob(image, 14, 2, 4, 4, GREEN);
  const pipeline = parsePreset({ schemaVersion: 1 });
  return runPipeline(image, pipeline, { sourcePath: 'player.png' }).manifest;
}

describe('godot exporter', () => {
  it('emits a SpriteFrames resource with one AtlasTexture per sprite', () => {
    const tres = buildSpriteFramesTres(buildManifest());
    expect(tres).toMatch(/^\[gd_resource type="SpriteFrames" load_steps=4 format=3\]$/m);
    expect(tres).toContain('[ext_resource type="Texture2D" path="atlas-0.png" id="1"]');
    expect(tres).toContain('[sub_resource type="AtlasTexture" id="AtlasTexture_1"]');
    // cells include padding+bleed margins: content 4x4 → cell 12x12; B packs at x=14
    expect(tres).toContain('region = Rect2(0, 0, 12, 12)');
    expect(tres).toContain('region = Rect2(14, 0, 12, 12)');
    expect(tres).toContain('"name": &"default"');
    expect(tres).toContain('"loop": true');
    expect(tres.endsWith('\n')).toBe(true);
    // sub_resource count matches sprites
    expect(tres.match(/\[sub_resource type="AtlasTexture"/g)).toHaveLength(2);
  });

  it('is deterministic and version-free (no uids, no timestamps)', () => {
    const a = buildSpriteFramesTres(buildManifest());
    const b = buildSpriteFramesTres(buildManifest());
    expect(a).toEqual(b);
    expect(a).not.toContain('uid=');
    expect(a).not.toContain(CORE_VERSION);
  });
});

describe('unity exporter', () => {
  const script = buildUnityImporterScript();

  it('generates the AssetPostprocessor reading atlas.json', () => {
    expect(script).toContain('class GameAssetForgeImporter : AssetPostprocessor');
    expect(script).toContain('OnPreprocessTexture');
    expect(script).toContain('"atlas.json"');
    expect(script).toContain('TextureImporterType.Sprite');
    expect(script).toContain('SpriteImportMode.Multiple');
    expect(script).toContain('SpriteAlignment.Custom');
    expect(script).toContain(`Generated by GameAsset Forge ${CORE_VERSION}`);
  });

  it('flips manifest top-left rects into Unity bottom-left space', () => {
    expect(script).toContain('pageHeight - sprite.rect.y - sprite.rect.height');
  });

  it('is statically well-formed: balanced braces, no stray template markers', () => {
    let depth = 0;
    for (const ch of script) {
      if (ch === '{') depth++;
      if (ch === '}') depth--;
      expect(depth).toBeGreaterThanOrEqual(0);
    }
    expect(depth).toBe(0);
    expect(script).not.toContain('@VERSION@');
  });
});
